language: clojure
script:
    - lein test
    - lein yagni
    - lein eastwood
    - lein cloverage
    - lein ring server-headless &
    - sleep 10
    - lein with-profile pact pact-verify
notifications:
  email: false
