sudo: required
services:
  - docker

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose run backend lein test
  - docker-compose run frontend yarn test

notifications:
  email:
    false
