sudo: required

services:
    - docker

jobs:
    include:
        - stage: Unit Tests
          script:
              - docker-compose run backend lein test
              - docker-compose run frontend yarn test
        - stage: Clean Code
          script:
              - docker-compose run backend lein yagni
        - stage: Code Coverage
          script:
              - docker-compose run backend lein cloverage -e persistence.persistence -e api.handler --fail-threshold 95
        - stage: End-to-End Tests
          if: branch = master
          script:
              - docker-compose run frontend yarn install # Prepare modules
              - docker-compose -f docker-compose.yml -f docker-compose.e2e.yml run e2e test-delayed
        - stage: Deploy
          if: branch = master AND type != pull_request
          script:
              - openssl aes-256-cbc -K $encrypted_cce65efc8ba2_key -iv $encrypted_cce65efc8ba2_iv -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
              - eval "$(ssh-agent -s)" #start the ssh agent
              - chmod 600 .travis/deploy_key.pem
              - cp .travis/known_hosts ~/.ssh/
              - ssh-add .travis/deploy_key.pem
              - git remote add deploy kenan@rhoton.es:~/Projects/card-game
              - git checkout master
              - git push deploy

notifications:
    email: false
