version: '2'
services:
    frontend:
        build: frontend
        restart: always
        ports:
            - "8880:8880"
        volumes:
            - ./frontend:/usr/src/app
            - ./configs:/usr/src/app/src/config/data
        depends_on:
            - backend
    backend:
        build: backend
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/usr/src/app
            - ./configs:/configs
            - lein-deps:/root/.m2
        links:
            - redis
    redis:
        image: redis
        restart: always
volumes:
    lein-deps:
