version: '3'
services:
    frontend:
        build: frontend
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/usr/src/app
    backend:
        build: backend
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/usr/src/app
        links:
            - redis
    redis:
        image: redis:alpine
        restart: always
