version: '3'
services:
    frontend:
        build: frontend
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/usr/src/app
            - ./configs:/usr/src/app/config/data
        depends_on:
            - backend
    backend:
        build: backend
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/usr/src/app
            - ./configs:/configs
            - lein-deps:/root/.m2
        links:
            - redis
    redis:
        image: redis:alpine
        restart: always
    e2e:
        build: e2e
        volumes:
            - ./e2e:/tests
            - ./configs:/configs
        links:
            - frontend
            - backend
        command: "/bin/true"
volumes:
    lein-deps:
