# Anything in this file should be considered 100% public as it is served to frontend
messages:
    out-of-turn: "Out of turn play"
    no-opp: "Waiting for an opponent"
    play: "Playing"
    wait: "Waiting for opponent's play"
    row-limit: "Can't play on this row"
    too-many-players: "Too many players"
    need-target: "A target is needed"
    invalid-target: "That's an invalid target"
    not-owned-card: "You don't own this card"
    no-row: "This row doesn't exist"
    invalid-id: "Wrong id"
