# Anything in this file should be considered 100% public as it is served to frontend
messages:
    out-of-turn: "Out of turn play"
    no-opp: "Waiting for an opponent"
    play: "Playing"
    wait: "Waiting for opponent's play"
    too-many-players: "Too many players"
servers:
    frontend: "frontend:8880"
    backend: "backend:3000"
